### PR TITLE
Removed folder creation

### PR DESCRIPTION
**Pull request by the-ventura**

### CODE REVIEW

**Comment by the-ventura** [comment]
Hi, thanks for the comment.
The port changes are because I get a auth error on qbit when running in any other port than the default one for some reason.
The folder creation changes are because under a vmware shared folder the permissions are tricky and Im running into an ansible permission error thing.
This was never meant to be a PR just a little forked repo with my own personal changes. :)

**Comment by the-ventura** [comment]
Also im using nzbget instead.

**Comment by robertbaker** [comment]
As for your port. You shouldn't. How are you connecting to qbittorrent? You
don't need to use the domain name. You just need qbittorrent:8080. if
you're getting an error there's something else going on and changing the
port is the wrong fix...

**Comment by the-ventura** [comment]
I get a 401 response whenever I try to set it to any port other than 8080. 
I searched around for a while and some users had the same issue so I did this small workaround to work in my specific use case.

**Comment by robertbaker** [comment]
That problem is actually because their CSRF protection is buggy, it won't
work well  with shielf. Uncheck the setting in the webui tab should fix it.

**Comment by the-ventura** [comment]
Hmm ok thanks, Ill try it later today!

**Pull request closed without merging**
